name: h_utils
version: 0.0.8
homepage: https://booza.app
description: Extend you code beyond reach with HUtils.

environment: 
  sdk: '>=2.6.0 <3.0.0'

dependencies: 
  equatable: ^2.0.0
  date_format: ^1.0.9
  logger: ^0.9.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter:

